// Données mockées pour l'aperçu du projet sans WordPress
import type { Article, MediaPartner } from './transformers'

export const mockMediaPartners: MediaPartner[] = [
  {
    id: "sport-med",
    name: "Sport MED",
    slug: "sport-med",
    tagline: "L'actualité du sport régional",
    description: "Sport, événements sportifs et actualité des clubs de Provence-Alpes-Côte d'Azur",
    longDescription: "Sport MED couvre l'actualité sportive de la région avec passion et expertise. Des matchs des équipes régionales aux grands événements sportifs, nous vous tenons au courant de tous les enjeux du sport local.",
    theme: "Sport & Loisirs",
    color: "from-slate-700 to-slate-900",
    icon: "Trophy",
    coverage: "Toute la région PACA",
    founded: "2015",
    website: "https://sport-med.fr",
    specialties: ["Football", "Rugby", "Athlétisme", "Événements sportifs", "Jeunesse"],
    team: "8 journalistes",
    audience: "60 000 lecteurs mensuels",
    bgImage: "/sport-med.webp",
  },
  {
    id: "marcelle",
    name: "Marcelle",
    slug: "marcelle",
    tagline: "Votre source d'actualité régionale",
    description: "Actualité générale, politique et initiatives de la région",
    longDescription: "Marcelle est un média généraliste couvrant tous les aspects de la vie régionale. De la politique locale aux initiatives citoyennes, nous décryptez l'actualité qui façonne notre territoire.",
    theme: "Actualité Générale",
    color: "from-purple-400 to-pink-300",
    icon: "Newspaper",
    coverage: "Provence-Alpes-Côte d'Azur",
    founded: "2018",
    website: "https://marcelle.fr",
    specialties: ["Politique", "Économie", "Société", "Culture", "Environnement"],
    team: "12 journalistes",
    audience: "75 000 lecteurs mensuels",
    bgImage: "/marcelle-logo.webp",
  },
  {
    id: "mprovence",
    name: "mprovence",
    slug: "mprovence",
    tagline: "Engagé naturel de bonnes idées",
    description: "Environnement, développement durable et nature en Provence",
    longDescription: "mprovence valorise les initiatives écologiques et la préservation des espaces naturels. Nous explorons les solutions durables et les bons gestes pour une Provence verte et respectueuse de la nature.",
    theme: "Environnement & Nature",
    color: "from-green-400 to-emerald-500",
    icon: "Leaf",
    coverage: "Provence",
    founded: "2016",
    website: "https://mprovence.fr",
    specialties: ["Écologie", "Agriculture bio", "Tourisme vert", "Aménagement territoire", "Biodiversité"],
    team: "6 journalistes",
    audience: "40 000 lecteurs mensuels",
    bgImage: "/LOGO-MPROVENCE-768x154.png.webp",
  },
  {
    id: "lehtv",
    name: "LEHTV",
    slug: "lehtv",
    tagline: "L'actualité du territoire",
    description: "Actualités hyperlocales et initiatives des territoires",
    longDescription: "LEHTM se concentre sur l'actualité hyperlocale avec des reportages en profondeur. Nous donnons une voix aux territoires et aux initiatives citoyennes souvent oubliées des grands médias.",
    theme: "Actualité Locale",
    color: "from-slate-900 to-slate-800",
    icon: "MapPin",
    coverage: "Toute la région PACA",
    founded: "2017",
    website: "https://lehtv.fr",
    specialties: ["Hyperlocal", "Initiatives citoyennes", "Vie de quartier", "Social", "Proximité"],
    team: "10 journalistes",
    audience: "45 000 lecteurs mensuels",
    bgImage: "/LEHTV-logo-medias.png.webp",
  },
  {
    id: "frequence-mistral",
    name: "Frequence Mistral",
    slug: "frequence-mistral",
    tagline: "Engagez naturel de bonnes idées",
    description: "Radio généraliste avec musique, infos et divertissement",
    longDescription: "Frequence Mistral est une radio généraliste proposant actualités, musique, infos pratiques et divertissement. Une fenêtre sur la région avec des émissions en direct et un lien constant avec les auditeurs.",
    theme: "Radio & Divertissement",
    color: "from-amber-400 to-yellow-500",
    icon: "Radio",
    coverage: "Provence-Alpes-Côte d'Azur",
    founded: "2012",
    website: "https://frequence-mistral.fr",
    specialties: ["Actualités", "Musique", "Jeux", "Infos pratiques", "Émissions spécialisées"],
    team: "15 animateurs",
    audience: "90 000 auditeurs mensuels",
    bgImage: "/frequence-mistral-logo.png.webp",
  },
  {
    id: "bleu-tomate",
    name: "bleu tomate",
    slug: "bleu-tomate",
    tagline: "Engagez naturel de bonnes idées",
    description: "Podcast et contenus audio innovants sur les enjeux régionaux",
    longDescription: "bleu tomate produit des contenus audio innovants et des podcasts explorant les enjeux de notre région. Du débat d'idées aux histoires inspirantes, nous créons du contenu audio engagé et de qualité.",
    theme: "Podcast & Audio",
    color: "from-green-600 to-green-700",
    icon: "Headphones",
    coverage: "Provence-Alpes-Côte d'Azur",
    founded: "2019",
    website: "https://bleu-tomate.fr",
    specialties: ["Podcasts", "Débat", "Histoires", "Reportages audio", "Enquêtes"],
    team: "5 producteurs",
    audience: "30 000 auditeurs mensuels",
    bgImage: "/Logo-bleue-tomates-medias.jpg.webp",
  },
]

export const mockArticles: Article[] = [
  {
    id: 1,
    title: "L'OM remporte une victoire spectaculaire face à Nice",
    excerpt: "Le match est allé en prolongation avec un but décisif en toute fin de rencontre. Une performance remarquable des Olympiens qui s'impose face aux Aiglons.",
    media: "Sport MED",
    mediaSlug: "sport-med",
    category: "Football",
    mainCategory: "sports",
    subCategory: "football",
    date: "2024-01-15",
    readTime: "5 min",
    image: "/football-match-stadium.png",
    slug: "ogc-nice-victoire-marseille",
    link: "/article/ogc-nice-victoire-marseille",
  },
  {
    id: 2,
    title: "Politique régionale: nouvelles mesures pour 2024",
    excerpt: "Les élus régionaux dévoilent leur programme pour les mois à venir. Focus sur les priorités économiques et environnementales de la région PACA.",
    media: "Marcelle",
    mediaSlug: "marcelle",
    category: "Politique",
    mainCategory: "actualites",
    subCategory: "politique",
    date: "2024-01-14",
    readTime: "7 min",
    image: "/regional-government-meeting.jpg",
    slug: "politique-regionale-2024",
    link: "/article/politique-regionale-2024",
  },
  {
    id: 3,
    title: "Initiative verte: nouvelle réserve naturelle en Provence",
    excerpt: "Les habitants se mobilisent pour protéger un espace naturel unique. Un projet citoyen qui voit le jour après plusieurs années de mobilisation.",
    media: "mprovence",
    mediaSlug: "mprovence",
    category: "Environnement",
    mainCategory: "environnement",
    subCategory: "nature",
    date: "2024-01-14",
    readTime: "6 min",
    image: "/nature-reserve-provence-green-forest.jpg",
    slug: "reserve-naturelle-provence",
    link: "/article/reserve-naturelle-provence",
  },
  {
    id: 4,
    title: "Vie de quartier: les initiatives qui changent Marseille",
    excerpt: "Découvrez les projets des habitants du quartier de la Plaine. Des initiatives citoyennes qui transforment le quotidien des Marseillais.",
    media: "LEHTM",
    mediaSlug: "lehtm",
    category: "Actualité Locale",
    mainCategory: "vie-locale",
    subCategory: "quartiers",
    date: "2024-01-13",
    readTime: "8 min",
    image: "/marseille-neighborhood-community.webp",
    slug: "initiatives-marseille-plaine",
    link: "/article/initiatives-marseille-plaine",
  },
  {
    id: 5,
    title: "Podcast: les entrepreneurs qui font la région",
    excerpt: "Écoutez les histoires inspirantes d'entrepreneurs locaux engagés. Des parcours qui montrent la vitalité économique de la région PACA.",
    media: "bleu tomate",
    mediaSlug: "bleu-tomate",
    category: "Podcast",
    mainCategory: "podcasts",
    subCategory: "interviews",
    date: "2024-01-13",
    readTime: "45 min",
    image: "/podcast-microphone-studio-recording.jpg",
    slug: "podcast-entrepreneurs-region",
    link: "/article/podcast-entrepreneurs-region",
  },
  {
    id: 6,
    title: "Musique: les talents régionaux à découvrir",
    excerpt: "Écoutez les nouveaux artistes mis en avant par Frequence Mistral. Une sélection éclectique qui reflète la diversité musicale de la région.",
    media: "Frequence Mistral",
    mediaSlug: "frequence-mistral",
    category: "Musique",
    mainCategory: "evenements",
    subCategory: "concerts",
    date: "2024-01-12",
    readTime: "4 min",
    image: "/live-music-concert-stage-lights.jpg",
    slug: "talents-musicaux-region",
    link: "/article/talents-musicaux-region",
  },
  {
    id: 7,
    title: "Marseille accueille un nouveau hub d'innovation technologique",
    excerpt: "Un espace de 5000m² dédié aux startups et à l'innovation ouvre ses portes dans le quartier de la Joliette. Un projet qui positionne Marseille comme pôle d'innovation.",
    media: "Marcelle",
    mediaSlug: "marcelle",
    category: "Économie",
    mainCategory: "actualites",
    subCategory: "economie",
    date: "2024-01-11",
    readTime: "6 min",
    image: "/modern-tech-hub-marseille.jpg",
    slug: "hub-innovation-marseille",
    link: "/article/hub-innovation-marseille",
  },
  {
    id: 8,
    title: "Festival de Cannes : la sélection officielle dévoilée",
    excerpt: "Découvrez les films en compétition pour la Palme d'Or lors de la 77e édition du festival. Une sélection qui promet de belles découvertes cinématographiques.",
    media: "Marcelle",
    mediaSlug: "marcelle",
    category: "Culture",
    mainCategory: "evenements",
    subCategory: "festivals",
    date: "2024-01-10",
    readTime: "5 min",
    image: "/cannes-red-carpet.png",
    slug: "festival-cannes-selection",
    link: "/article/festival-cannes-selection",
  },
  {
    id: 9,
    title: "Tourisme durable : la Provence montre l'exemple",
    excerpt: "Des initiatives locales transforment le secteur touristique. Hébergements éco-responsables, circuits courts et mobilité douce au programme.",
    media: "mprovence",
    mediaSlug: "mprovence",
    category: "Tourisme",
    mainCategory: "environnement",
    subCategory: "ecologie",
    date: "2024-01-09",
    readTime: "6 min",
    image: "/nature-reserve-provence-green-forest.jpg",
    slug: "tourisme-durable-provence",
    link: "/article/tourisme-durable-provence",
  },
  {
    id: 10,
    title: "Rugby : le RCT prépare sa saison européenne",
    excerpt: "L'équipe toulonnaise se prépare pour les phases finales de la Champions Cup. Analyse tactique et interview exclusive du capitaine.",
    media: "Sport MED",
    mediaSlug: "sport-med",
    category: "Rugby",
    mainCategory: "sports",
    subCategory: "rugby",
    date: "2024-01-08",
    readTime: "7 min",
    image: "/football-match-stadium.png",
    slug: "rct-saison-europeenne",
    link: "/article/rct-saison-europeenne",
  },
  {
    id: 11,
    title: "Gastronomie : les chefs étoilés de la région PACA",
    excerpt: "Portrait des nouvelles étoiles de la cuisine méditerranéenne. Découvrez les restaurants qui font rayonner notre terroir.",
    media: "Marcelle",
    mediaSlug: "marcelle",
    category: "Gastronomie",
    mainCategory: "evenements",
    subCategory: "culture",
    date: "2024-01-07",
    readTime: "8 min",
    image: "/regional-government-meeting.jpg",
    slug: "chefs-etoiles-paca",
    link: "/article/chefs-etoiles-paca",
  },
  {
    id: 12,
    title: "Éducation : nouvelle filière tech au lycée Thiers",
    excerpt: "Le lycée marseillais lance une formation innovante en cybersécurité. Un partenariat unique avec les entreprises du numérique local.",
    media: "LEHTM",
    mediaSlug: "lehtm",
    category: "Éducation",
    mainCategory: "actualites",
    subCategory: "education",
    date: "2024-01-06",
    readTime: "5 min",
    image: "/marseille-neighborhood-community.webp",
    slug: "filiere-tech-lycee-thiers",
    link: "/article/filiere-tech-lycee-thiers",
  },
]

export function getMockArticlesByMedia(mediaSlug: string): Article[] {
  return mockArticles.filter(article => article.mediaSlug === mediaSlug)
}

export function getMockArticleBySlug(slug: string): Article | undefined {
  return mockArticles.find(article => article.slug === slug)
}

